#!/bin/bash
# $1 - lang
# $2 - file

echo usage addocr2djvu lang file.djvu
echo lang = eng, rus, rus-eng

for f in "$2"
do
  cp "$f" tmp.djvu
	djvused tmp.djvu -e 'remove-txt' -s
	for p in $(seq 1 $(djvused -e n tmp.djvu))
	do
		ocrodjvu -p $p --in-place --render=all --engine=tesseract --language=$1 tmp.djvu
		# ocrodjvu -p $p --in-place --render=all --engine=cuneiform --language=$1 tmp.djvu
	done
  mv tmp.djvu "$f"
done
