#!/bin/bash
# $1 - lang
# $2 - file

echo usage addocr2djvu lang file.djvu
echo lang = eng, rus, rus-eng

for f in "$2"
do
	djvused "$f" -e 'remove-txt' -s
	for p in $(seq 1 $(djvused -e n "$f"  ))
	do
		ocrodjvu -p $p --in-place --render=all --engine=cuneiform --language=$1 "$f"
	done
done

