#!/bin/bash
#http://askubuntu.com/questions/46233/converting-djvu-to-pdf
echo "Bash version ${BASH_VERSION}..."

for f in *.djvu;
do

	# prepare, to hold your colour
	mkdir ./tmp
	cp "$f" ./tmp/in.djvu
	cd tmp

	num=$(djvm -l in.djvu | grep PAGE | wc -l) # number of pages being processed
	for i in $(seq -w $num)
	do
		djvu2hocr -p $i in.djvu | sed 's/ocrx/ocr/g' > t$i.html # extract ocr
		ddjvu -format=tiff -page=$i in.djvu t$i.tif	# extract image
	done

	pdfbeads -o out.pdf

	# clean
	mv out.pdf "../$f.pdf"
	cd ..
	rm -r ./tmp
done
