#!/bin/bash
#http://unix.stackexchange.com/questions/26195/how-to-split-each-page-of-a-djvu-file
# 
# dependencies <lib> : <tool>
# djvulibre-bin : ddjvu, cjb2, djvm
# imagemagick : convert
# awk : awk
# coreutils : mktemp
echo Usage: djvusplit PAGEFROM PAGETO FILE.DJVU
echo Example: djvusplit 3 10 file.djvu

# pfrom = $1
# pto = $2
# file $3

TFLDR=$(mktemp -d -t djvusplit.XXXXX)
echo "Temporary folder: "$TFLDR
cp "$3" $TFLDR/

for i in $(seq -w $2 -1 $1)
do
	# extract bifold page
	ddjvu -format=tiff -page=$i $TFLDR/"$3" $TFLDR/t$i.tiff

	# split it in two tiff's & convert to one djvu
	convert -crop 2x1@ $TFLDR/t$i.tiff $TFLDR/t$i-%d.tiff
	convert $TFLDR/t$i-0.tiff $TFLDR/t$i-0.pbm
	convert $TFLDR/t$i-1.tiff $TFLDR/t$i-1.pbm
	cjb2 $TFLDR/t$i-0.pbm $TFLDR/t$i-0.djvu
	cjb2 $TFLDR/t$i-1.pbm $TFLDR/t$i-1.djvu
	djvm -i $TFLDR/t$i-0.djvu $TFLDR/t$i-1.djvu 2

	# replace bifold page with two pages
	djvm -d $TFLDR/$3 $i
	djvm -i $TFLDR/$3 $TFLDR/t$i-0.djvu $i

	# clean unnecessary (tiff, pbm, djvu) files
	rm $TFLDR/t*
done

# total clean
mv $TFLDR/$3 "./$(echo $3 | awk -F "." '{print $1}')_splitted.djvu"
rm -r $TFLDR

